# Generated by Django 5.1.2 on 2025-11-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_sitesetting_homesection_carouselitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesection',
            name='kind',
            field=models.CharField(choices=[('category', 'By Category'), ('newest', 'Newest Products'), ('popular', 'Popular Products'), ('trend', 'Trend Products')], default='category', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='popularity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='trend_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
