# Generated by Django 5.1.2 on 2025-11-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_homesection_kind_product_popularity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesection',
            name='columns',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='home_columns',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
