# Generated by Django 5.1.2 on 2025-11-05 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_homesection_columns_sitesetting_home_columns'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselitem',
            options={'ordering': ['order', 'id'], 'verbose_name_plural': 'Carousel items'},
        ),
        migrations.AlterModelOptions(
            name='homesection',
            options={'ordering': ['order', 'id'], 'verbose_name_plural': 'Home sections'},
        ),
    ]
