# Generated by Django 5.1.2 on 2025-11-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_carouselitem_options_alter_homesection_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='home_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
