# Generated by Django 5.1.2 on 2025-11-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_sitesetting_home_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='carousel_animation',
            field=models.CharField(choices=[('none', 'None'), ('slide', 'Slide'), ('fade', 'Fade')], default='slide', max_length=16),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='carousel_speed_ms',
            field=models.PositiveIntegerField(default=3000),
        ),
    ]
