# Generated by Django 5.1.2 on 2025-11-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_sitesetting_carousel_animation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='show_carousel',
            field=models.BooleanField(default=True),
        ),
    ]
