# Generated by Django 5.1.2 on 2025-11-05 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_sitesetting_show_carousel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='show_carousel',
        ),
    ]
