# Generated by Django 5.1.2 on 2025-11-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_sitesetting_show_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='selected_carousel',
            field=models.ManyToManyField(blank=True, related_name='sites_selected', to='shop.carouselitem'),
        ),
    ]
