# Generated by Django 5.1.2 on 2025-11-05 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_sitesetting_selected_carousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('animation', models.CharField(choices=[('none', 'None'), ('slide', 'Slide'), ('fade', 'Fade')], default='slide', max_length=16)),
                ('speed_ms', models.PositiveIntegerField(default=3000)),
                ('order', models.PositiveIntegerField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousels', to='shop.sitesetting')),
            ],
            options={
                'verbose_name': 'Carousel',
                'verbose_name_plural': 'Carousels',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='selected_carousels',
            field=models.ManyToManyField(blank=True, related_name='sites_selected', to='shop.carousel'),
        ),
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=150)),
                ('image_url', models.URLField()),
                ('link_url', models.URLField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('carousel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='shop.carousel')),
            ],
            options={
                'verbose_name': 'Carousel slide',
                'verbose_name_plural': 'Carousel slides',
                'ordering': ['order', 'id'],
            },
        ),
    ]
