# Generated by Django 5.1.2 on 2025-11-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_carousel_sitesetting_selected_carousels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='animation',
            field=models.CharField(choices=[('none', 'None'), ('slide', 'Slide'), ('fade', 'Fade'), ('slide_fade', 'Slide + Fade')], default='slide', max_length=16),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='carousel_animation',
            field=models.CharField(choices=[('none', 'None'), ('slide', 'Slide'), ('fade', 'Fade'), ('slide_fade', 'Slide + Fade')], default='slide', max_length=16),
        ),
    ]
