# Generated by Django 5.1.2 on 2025-11-05 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_carousel_animation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='source_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category'),
        ),
        migrations.AddField(
            model_name='carousel',
            name='source_limit',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='carousel',
            name='source_ordering',
            field=models.CharField(choices=[('newest', 'Newest'), ('popular', 'Popular'), ('trend', 'Trend'), ('price_asc', 'Price: Low to High'), ('price_desc', 'Price: High to Low')], default='newest', max_length=20),
        ),
        migrations.AddField(
            model_name='carousel',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual (slides below)'), ('category', 'From Category Products')], default='manual', max_length=20),
        ),
    ]
