# Generated by Django 5.1.2 on 2025-11-05 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_carousel_source_category_carousel_source_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='featured_carousel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_on', to='shop.carousel'),
        ),
    ]
