# Generated by Django 5.1.2 on 2025-11-05 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_sitesetting_featured_carousel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='featured_carousel',
        ),
        migrations.CreateModel(
            name='HomeCarouselSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('carousel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.carousel')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_sections', to='shop.sitesetting')),
            ],
            options={
                'verbose_name': 'Home section from carousel',
                'verbose_name_plural': 'Home sections from carousels',
                'ordering': ['order', 'id'],
            },
        ),
    ]
