# Generated by Django 5.1.2 on 2025-11-05 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_remove_sitesetting_featured_carousel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='source_category',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='source_limit',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='source_ordering',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='source_type',
        ),
        migrations.CreateModel(
            name='CarouselCategorySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.PositiveIntegerField(default=8)),
                ('ordering', models.CharField(choices=[('newest', 'Newest'), ('popular', 'Popular'), ('trend', 'Trend'), ('price_asc', 'Price: Low to High'), ('price_desc', 'Price: High to Low')], default='newest', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('carousel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_sources', to='shop.carousel')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
            options={
                'verbose_name': 'Carousel from category',
                'verbose_name_plural': 'Carousels from category',
                'ordering': ['order', 'id'],
            },
        ),
    ]
