# Generated by Django 5.1.2 on 2025-11-07 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_product_low_stock_threshold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStyleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('card_bg_color', models.CharField(blank=True, default='#ffffff', max_length=20)),
                ('price_color', models.CharField(blank=True, default='#2563eb', max_length=20)),
                ('button_variant', models.CharField(choices=[('primary', 'Primary'), ('outline', 'Outline')], default='primary', max_length=20)),
                ('rounded_px', models.PositiveIntegerField(default=10)),
                ('image_height_px', models.PositiveIntegerField(default=200)),
                ('show_badges', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Product style template',
                'verbose_name_plural': 'Product style templates',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='style_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.productstyletemplate'),
        ),
    ]
