# Generated by Django 5.1.2 on 2025-11-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_productstyletemplate_product_style_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstyletemplate',
            name='outline_color',
            field=models.CharField(blank=True, default='#2563eb', max_length=20),
        ),
        migrations.AddField(
            model_name='productstyletemplate',
            name='primary_color',
            field=models.CharField(blank=True, default='#2563eb', max_length=20),
        ),
    ]
