# Generated by Django 5.1.2 on 2025-11-08 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_productstyletemplate_outline_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='floating_cart_bg',
            field=models.CharField(blank=True, default='#2563eb', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='floating_cart_border',
            field=models.CharField(blank=True, default='#2563eb', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='floating_cart_position',
            field=models.CharField(choices=[('br', 'Bottom Right'), ('bl', 'Bottom Left')], default='br', max_length=2),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='floating_cart_text',
            field=models.CharField(blank=True, default='#ffffff', max_length=20),
        ),
    ]
