# Generated by Django 5.1.2 on 2025-11-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_sitesetting_floating_cart_bg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='floating_cart_radius',
            field=models.PositiveIntegerField(default=999),
        ),
    ]
