# Generated by Django 5.1.2 on 2025-11-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_sitesetting_menu_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='menu_card_bg_color',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='menu_card_border_color',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='menu_card_border_px',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='menu_card_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='menu_card_padding_px',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='menu_card_radius_px',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='menu_card_shadow',
            field=models.BooleanField(default=True),
        ),
    ]
