# Generated by Django 5.1.2 on 2025-11-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_sitesetting_menu_card_bg_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Payment', max_length=150)),
                ('description', models.TextField(blank=True, default='Demo payment form. Integrate your gateway later.')),
                ('button_label', models.CharField(blank=True, default='Pay', max_length=100)),
                ('success_message', models.CharField(blank=True, default='Payment successful! Thank you for your order.', max_length=200)),
                ('enabled', models.BooleanField(default=True)),
                ('require_login', models.BooleanField(default=False)),
                ('test_mode', models.BooleanField(default=True)),
                ('gateway_name', models.CharField(blank=True, default='Demo', max_length=100)),
                ('currency', models.CharField(blank=True, default='USD', max_length=10)),
                ('fixed_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fee_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Payment setting',
                'verbose_name_plural': 'Payment settings',
            },
        ),
    ]
