# Generated by Django 5.1.2 on 2025-11-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_paymentsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=150)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('test_mode', models.BooleanField(default=True)),
                ('button_label', models.CharField(blank=True, default='Pay', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('config_json', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Payment gateway',
                'verbose_name_plural': 'Payment gateways',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='carousel',
            name='single_slider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carousel',
            name='slider_height_px',
            field=models.PositiveIntegerField(default=360),
        ),
    ]
