# Generated by Django 5.1.2 on 2025-11-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_paymentgateway_carousel_single_slider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='animation',
            field=models.CharField(choices=[('none', 'None'), ('slide', 'Slide'), ('fade', 'Fade'), ('slide_fade', 'Slide + Fade'), ('zoom_in', 'Zoom In'), ('zoom_out', 'Zoom Out'), ('skew', 'Skew'), ('kenburns', 'Ken Burns')], default='slide', max_length=16),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='carousel_animation',
            field=models.CharField(choices=[('none', 'None'), ('slide', 'Slide'), ('fade', 'Fade'), ('slide_fade', 'Slide + Fade'), ('zoom_in', 'Zoom In'), ('zoom_out', 'Zoom Out'), ('skew', 'Skew'), ('kenburns', 'Ken Burns')], default='slide', max_length=16),
        ),
    ]
