# Generated by Django 5.1.2 on 2025-11-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_alter_carousel_animation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, null=True, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='order_counter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='order_prefix',
            field=models.CharField(blank=True, default='ORD-', max_length=20),
        ),
    ]
